### ISSUE TITLE
How to generate a null model in MNI152 space through burt2020

### ISSUE THREAD

**Issue by zzcpage** [netneurolab/neuromaps#119]
### Description of issue

I want to generate a null model of the schafer200 graph in MNI152 space. I use burt2020 to generate a null model with the code nulls.burt2020 (schafer_data, atlas='mni152 ', density='2mm', nperm=1, seed=1234), but it prompts No space left on device. How can I solve this problem?

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by HusBunia** [comment]
> Hi @zzcpage thanks for reaching out. Right now your best way forward is likely to use [brainSMASH](https://brainsmash.readthedocs.io/en/latest/), the oirignal Python implementation of these parametrized nulls. A bit of history: the parametrized null functions in neuromaps were originally implemented for the volumetric case. We then added the parcellated case, but right now the function is taking the highly inefficient route of first computing a massive distance matrix (nvoxels x nvoxels), then parcellating that distance matrix. The better way would be to just calculate the distance matrix at the parcellated level to avoid calculating the nvoxel x nvoxel matrix (which takes both a lot of time to compute but also - as you noticed - a lot of space).
> 
> Anyways, we're aware of this issue that makes these parametrized nulls highly inefficient to use - we're working on fixing it and hopefully an updated version will be out soon. In the meantime, it is probably much easier for you to directly use brainSMASH to generate these nulls.
> 
> Small side note: since this is at the cortical level, you could use the spins instead of the parametrized nulls.
> 
> Small side note 2: to generate parcellated nulls you need to include the `parcellation` parameter. Once you include this, you won't get the "No space left on device" error but... it will run for ages (because it is computing a nvoxel x nvoxel distance matrix).
> 
> Hope that helps!
> 
> Justine

Hi @justinehansen, 
I included the parcellation parameter, but it gave me the same error. 
According to your resonse, does this mean that I can directly generate a permutation matrix for volumetric images using the  cortical centroids from surface parcellations? 

Thanks

**Comment by justinehansen** [comment]
Hi @HusBunia , I'm not sure I understand your question.
If you want to generate nulls for a volumetric image, it will take a lot of time and space because the function needs to create a region x region distance matrix. In volumetric images, this is nvoxels x nvoxels, which is massive.

If you want to generate nulls for a _cortical_ parcellation, you could just use the spins which are quicker and easier to use. If you specifically want the parametric nulls, I recommend using brainSMASH directly (while the neuromaps team fixes the slow distance matrix generation in these nulls) where you will input a region x region distance matrix yourself (using parcel centroids).

Parcel centroids can be estimated in multiple ways; I recommend checking [this](https://netneurotools.readthedocs.io/en/latest/generated/netneurotools.freesurfer.find_parcel_centroids.html) out.

Let me know if this doesn't answer your question.
