### ISSUE TITLE
mismatch between fsaverage and fslr

### ISSUE THREAD

**Issue by pinilorenzo** [netneurolab/neuromaps#135]
### Description of issue

I have a .mgh file (converted to .gii using mri_convert) representing a <significance_map> in fsaverage space. I am attempting to visualize it on the veryinflated template of the fslr. I followed this procedure:

fslr_L = transforms.fsaverage_to_fslr('cache.th40.pos.sig.cluster.lh.gii', 
                                    '32k', method='nearest', hemi='L')
fslr_R = transforms.fsaverage_to_fslr('cache.th40.pos.sig.cluster.Rh.gii', 
                                    '32k', method='nearest', hemi='R')
fslr rh, = fslr_R
fslr_lh, = fslr_L
fslr_agg=np.concatenate([fslr_lh.agg_data(),fslr_rh.agg_data()])

fslr = datasets.fetch_atlas(atlas='fslr', density='32k')
lh, rh =fslr['veryinflated']
p = Plot(lh,rh, views=['medial', 'lateral'], flip=False, zoom=1.2)
p.add_layer(fslr_agg, zero_transparent=True, as_outline=False, 
            cbar=True, cmap='Reds')
p.build()

The process runs successfully, and I obtain a result. However, upon comparing this result with the fsaverage inflated in freeview, significant differences emerge. The mapping appears in entirely different regions, such as the anterior vs. posterior cingulate and the temporal gyrus in fslr but not in fsaverage. What might be incorrect in the above code?

Thanks,
L

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hi @pinilorenzo, 

Sorry for the long delay. There does not seem to be any error in your code. To test the `fsaverage_to_fslr` function, I also tried to transform the fsaverage maps stored in neuromaps to fsLR, and it worked as expected. Could the differences be due to the viewer you used to plot your results?

I guess that it's also your hypothesis: you opened [an issue](https://github.com/danjgale/surfplot/issues/30) on the Surfplot repo last week, where you show that you get inconsistent results between surfplot and freeview even when you don't do any transformation.
