### ISSUE TITLE
Surface-to-volume transformations

### ISSUE THREAD

**Issue by Melissa1909** [netneurolab/neuromaps#152]
### Description of issue

Hi everyone, 
is it also possible to transform surfaces to volume with neuromaps (e.g., fsaverage_to_mni152)? I did not find a function in the API for that. Is there another way to do it (e.g., using nibabel)?
Thank you! 
Best, Melissa

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Melissa, neuromaps doesn't implement surface to volume transforms, primarily because it would involve upsampling a lot of data (there are a lot more voxels in a volumetric image than vertices in a surface). I'm not personally familiar with any surface-to-volume transformations but I found [this](https://github.com/miykael/parcellation_fragmenter/issues/32) conversation which might be relevant to you?

**Comment by Melissa1909** [comment]
Thank you!
