### ISSUE TITLE
Best Practices for using Neuromaps

### ISSUE THREAD

**Issue by BAshinoff** [netneurolab/neuromaps#159]
### Description of issue

Hi,

Thank you again for a great toolbox!

I was hoping you could clarify for me what best practices are for using Neuromaps since I have seen a few conflicting recommendations.

As an example, I have a map in MNI152 space and I want to compare it to **ALL** of the annotations in neuromaps for an exploratory analysis.

Should I...

1) Transform/resample my MNI152 map into the space of the annotations to generate the nulls and compare the images. My understanding is that this is ideal, but there are many annotations in volume space, and the parametric null models are very resource and computationally expensive. 

2) Convert everything into a single space, ideally a surface space like fsaverage since that allows me to use the non-parametric null models? The Neuromaps paper has an analysis near the end suggesting this should be good enough since transforming the space should not substantially affect the results, but I also wanted to check that I understood that correctly.

Assuming that I want to use my results in a publication, is it critical/required to do the analyses in the annotation space or can I transform everything into a common space? 

Thanks for your advice and help!

Cheers,
Brandon

### Code of Conduct

- [x] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Brandon,

great question - unfortunately there's no catch-all answer but here are some pointers.

* if non-neocortical regions are relevant to your analysis, then everything that _isn't_ in MNI space won't be that useful. 
* if you don't mind removing non-neocortical regions, then I think it's better to do the exploratory analysis in a single common space (probably the space of the lowest-resolution map in neuromaps, so you're not upsampling any data). This way you can compare your correlations + p-values across comparisons with equal number of observations (brain regions) instead of comparing a correlation between maps of 164k vertices with a correlation between maps of 4k vertices.
* If you also don't mind if the data is parcellated, then what I would do is parcellate everything to a much coarser resolution (e.g. 100-1000 regions in the Schaefer parcellation). This will mitigate a few things e.g. PET maps suffer from PVEs when transformed to the surface but these issues are much less of a problem when working at the resolution of parcels. Also doing a million spin tests with let's say 400-parcel maps instead of 4000+ vertices will be pretty quick.

so - if it were me, I would do option 3, but it's a tradeoff with (1) losing subcortex/cerebellum, and (2) losing dense sampling of the brain

**Comment by BAshinoff** [comment]
Thank you!!!
