### ISSUE TITLE
Subcortical structure inclusion and parcellated data

### ISSUE THREAD

**Issue by zqsha** [netneurolab/neuromaps#25]
### Description of issue

Thanks for developing such an amazing toolbox. I just have a couple of questions.
1. I was wondering whether the neuromaps in this toolbox include subcortical regions. If I input a volume-based map to do the correlation analysis, I guess subcortical regions would be removed. Right?
2. I have a parcellated brain map AA (e.g. Desikan-Killiany). When I perform the correlation analysis, do I need to first parcellate the neuromaps in the toolbox to the Desikan-Killiany atlas? And then perform the correlation analysis with map AA?

Thanks,
Cain

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Cain,

Thanks for your interest in `neuromaps`!
1. Most of the brain annotations included in neuromaps are surface based and only contain cortical data but the volumetric (MNI152) data do contain subcortical measures. Neuromaps is generally only useful for cortex-based analyses though, since it work with cortical surfaces so much. Any time an analysis requires a comparison between volumetric and surface data (i.e. a transformation from volume to surface), only cortical regions are considered. However (!) one caveat is that if you compare two volumetric images, `neuromaps` will correlate all the data which in this case would be both cortical and subcortical regions.
2. The `compare_images` function requires both maps to be in the same space (or parcellation), so you would need to parcellate first. I recommend `neuromaps.parcellate.Parcellater` 🙂 

Hope that helps, and feel free to reach out with more questions.

Justine
