### ISSUE TITLE
[BUG] Spatial null maps for volumetric data

### ISSUE THREAD

**Issue by LeonDLotter** [netneurolab/neuromaps#27]
### Issue summary

When trying to generate spatial null maps for volumetric data (voxel-wise and parcellated), I encountered three different error messages in the process.

### Detailed issue description

First, thank you for developing this toolbox! It's exactly what I needed for my current and planned projects. :)
Setup: macOS Monterey 12.0.1, python 3.8.8, ran in Anaconda/Spyder

**1. Spatial null maps for volumetric, voxel-wise data:**  

 When running the example from the docs:
 ```python
from neuromaps.datasets import fetch_annotation
from neuromaps.nulls import burt2020

neurosynth_mni152 = fetch_annotation(source='neurosynth')
nulls = burt2020(neurosynth_mni152, atlas='MNI152', density='3mm',
                 n_perm=100, seed=1234)
print(nulls.shape)

>>> ValueError: Provided `data` array must have same affine as specified MNI152 atlas
```

I fixed that via resampling the neurosynth_mni152 map:
```python
from neuromaps.datasets import fetch_annotation, fetch_mni152
from neuromaps.resampling import resample_images

neurosynth_mni152 = fetch_annotation(source='neurosynth')
mni_brainmask = str(fetch_mni152('3mm').brainmask)
neurosynth_mni152_res, _ = resample_images(src=neurosynth_mni152, 
                                           trg=mni_brainmask, 
                                           src_space='MNI152', trg_space='MNI152',
                                           method='linear', resampling="transform_to_trg")
nulls = burt2020(neurosynth_mni152_res, atlas='MNI152', density='3mm',
                 n_perm=100, seed=1234)
print(nulls.shape)

>>> File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 453, in _vol_surrogates
>>>    dist[n] = xyz_dist[index[n]]
>>> IndexError: index 1 is out of bounds for axis 0 with size 1
```

**2. Spatial null maps for volumetric, parcellated data:**  

I tried to parcellate the data via a volumetric parcellation (Schaefer2018 - 100 parcels), to avoid the first error above, I resampled both the neurosynth map and the parcellation to the MNI152-atlas. 
```python
from neuromaps.datasets import fetch_annotation, fetch_mni152
from neuromaps.resampling import resample_images
from neuromaps.parcellate import Parcellater
from neuromaps.nulls import burt2020

neurosynth_mni152 = fetch_annotation(source='neurosynth')
atlas = 'Schaefer2018_100Parcels_7Networks_order_FSLMNI152_2mm.nii.gz'
mni_brainmask = str(fetch_mni152('3mm').brainmask)
neurosynth_mni152_res, _ = resample_images(src=neurosynth_mni152, 
                                           trg=mni_brainmask, 
                                           src_space='MNI152', trg_space='MNI152',
                                           method='linear', resampling="transform_to_trg")
atlas_res, _ = resample_images(src=atlas, trg=mni_brainmask, 
                               src_space='MNI152', trg_space='MNI152',
                               method='nearest', resampling="transform_to_trg")
parc = Parcellater(atlas_res, 'mni152')
neurosynth_mni152_parc = parc.fit_transform(neurosynth_mni152_res, 'mni152')
```
Then I ran the null map generation - as I was not sure if the function needs the parcellated data or the original volumetric data, I tried both: 
```python
nulls_parc = burt2020(neurosynth_mni152_parc, atlas='mni152', density='3mm', 
                      parcellation=atlas_res, n_perm=100, seed=1234)

>>> ValueError: Provided `data` array must have same affine as specified MNI152 atlas
```

```python
nulls_parc = burt2020(neurosynth_mni152_res, atlas='mni152', density='3mm', 
                      parcellation=atlas_res, n_perm=100, seed=1234)
# after a pretty long time:
>>> 
  File "<ipython-input-26-560a67021188>", line 19, in <module>
    nulls_parc = burt2020(neurosynth_mni152_res, atlas='mni152', density='3mm',

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 572, in burt2020
    return _make_surrogates(data, 'burt2020', atlas=atlas, density=density,

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 487, in _make_surrogates
    hsurr = Base(hdata, hdist, seed=seed, **kwargs)(n_perm, 50).T

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/brainsmash/mapgen/base.py", line 65, in __init__
    self.D = D

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/brainsmash/mapgen/base.py", line 329, in D
    check_distmat(D=x_)

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/brainsmash/utils/checks.py", line 93, in check_distmat
    if not np.allclose(D, D.T):

  File "<__array_function__ internals>", line 5, in allclose

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/numpy/core/numeric.py", line 2256, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))

  File "<__array_function__ internals>", line 5, in isclose

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/numpy/core/numeric.py", line 2365, in isclose
    return within_tol(x, y, atol, rtol)

  File "/Applications/Anaconda/anaconda3/lib/python3.8/site-packages/numpy/core/numeric.py", line 2346, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))

ValueError: operands could not be broadcast together with shapes (68038,100) (100,68038) 
```

I don`t know whether I made mistakes - then I am sorry for bothering you. :) It would be great if you could point me to an answer to my problems.
Thank you very much for your great work! Best regards
Leon

[Schaefer2018_100Parcels_7Networks_order_FSLMNI152_2mm.nii.gz](https://github.com/netneurolab/neuromaps/files/7854256/Schaefer2018_100Parcels_7Networks_order_FSLMNI152_2mm.nii.gz)

### Steps to reproduce issue

```python
see above
```

### Software version

0.0.1

### What operating system were you using when you encountered this issue?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hi Leon, 
You did not make any mistake. Those are indeed bugs and we're currently working on fixing them. We are so sorry that you encountered so many of them. I should make a Pull Request in the next couple of days that will hopefully fix all of the issues you encountered. 

That being said, thank you so much for having taken the time to try all these different alternatives. It was very helpful to us when trying to figure out what was wrong. 

Stay tuned for the Pull Request :)

**Comment by LeonDLotter** [comment]
Hi Vince,
Thanks a lot for your answer! And no problem, happy to help. :)

**Comment by VinceBaz** [comment]
Hi Leon, I'll submit the Pull Request very soon. I'll explain here why you got your errors and how the changes we've made will fix the issues.

For the **first Error** (`ValueError: Provided 'data' array must have same affine as specified MNI152 atlas`), the issue was that the two maps, while being both in MNI152 space, did not have the same density. The neurosynth map had a resolution of 2mm while the brainmask had a resolution of 3mm (since you used `density='3mm'`). Your thinking was therefore correct that in such a case, we'd first need to resample one of the two maps so that they have the same density. Alternatively, using  `density='2mm'`, which you might have tried, should have worked, i.e.:

`nulls = burt2020(neurosynth_mni152, atlas='MNI152', density='2mm', n_perm=100, seed=1234)`.

However, with the current version of neuromaps, it does not. That is because the neurosynth map and the brainmask use two different "versions" of the MNI atlas. The neurosynth map uses the 6Asym version while the brainmask used the 2009c version, which means that the `shape` of the two atlases were different. We've added brainmasks for the 6Asym versions of the MNI152 atlases. From now on, the function will look at the shape of the data and decide whether to use the 6Asym brainmask or the MNI152 brainmask. So from now on, you should not have to explicitly call the `resample_image()` function if the `density` parameter is correct (`2mm` in the case of the neurosynth map).

Also, we've decided that it would perhaps be simpler for the user if the resampling process were to happen behind the scene. So now, if the user's brainmap has a density that is different from the density passed using the ` density` argument, then the function will call the `mni152_to_mni152() ` function to resample the 2009c brain mask to the shape of the user's brainmap instead of returning an error. This would however not be optimal if the brainmap is actually using the 6Asym version, so we really encourage inputing the correct `density` value when calling the null function. 


For the **second error** (`IndexError: index 1 is out of bounds for axis 0 with size 1`), this was a very straight forward bug where our code indexed the wrong axis. This was easily fixed. 

The **third error** (`ValueError: Provided `data` array must have same affine as specified MNI152 atlas`) is the same as the first one.  The way you did it was however correct: **the input data should indeed be already parcellated**. 

The **fourth error** (`ValueError: operands could not be broadcast together with shapes (68038,100) (100,68038)`) was again a stupid bug and should now be fixed. Note that **it is however normal that it takes a very long time to run.** That being said, here, even without a bug, the function would still have returned an error since when using a parcellation, the function expects `data` to be array-like, and not a Nifti image. We now explicitly raise an error when that is the case so that the user does not have to wait a couple of hours for nothing. 

Finally, I think it's important to let you know that in the process of generating Burt2020 nulls, **there is a temporary memmap array that is created and saved in the user's %Temp% folder.** When everything goes as planned, this temporary file should be deleted at the end. However, if the user encounters an error, this file might not be deleted. Since it can be really large I highly recommend that you look into your %Temp% folder to see whether there are some large memmap arrays, which you should delete if it is the case.

Again, we are so sorry that you encountered all these bugs, and we hope that they will now be resolved and that you will enjoy using the toolbox in the future :)

**Comment by VinceBaz** [comment]
The Pull Request has been merged and all issues should now be fixed. Thank you again for your comments! I'll now close this Issue, and feel free to let us know if you encounter any other bug!

**Comment by LeonDLotter** [comment]
Hi Vince,
Thank you very much for your detailed explanations! Indeed, now my examples work as expected, but - as you wrote - do indeed take a lot of time. 😄 
The first error ```ValueError: Provided 'data' array must have same affine as specified MNI152 atlas``` actually also occured when both maps were sampled to 2mm. I just accidentally copy-and-pasted the wrong code in here. So the MNI152-versions mismatch must have caused the problem.
I will certainly use your toolbox in my future projects!
