### ISSUE TITLE
Index out of bounds error when trying to get nulls for parcellated data

### ISSUE THREAD

**Issue by m-petersen** [netneurolab/neuromaps#29]
### Description of issue

Hey there,

at first thanks for your awesome work!

My neuromaps version is '0.0.1+3.g4e95807'

Currently I am aiming for spin permutation testing of schaefer400 parcellated data. Following your tutorial (https://netneurolab.github.io/neuromaps/user_guide/nulls.html#nulls-with-parcellated-data) I reproduced the steps with the schaefer atlas. First I fetched the schaefer labels from the enigma toolbox and the atlas-to-surface (conte69) mapping as provided with brainspace. Then I convert the mapping to gifti images as required. `nulls.alexander_bloch` then raises an error which for me points to a dimension mismatch.

```
IndexError: index 400 is out of bounds for axis 0 with size 400
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_10798/48594046.py in <module>
      1 rotated = nulls.alexander_bloch(schaefer_labels, atlas='fsLR', density='32k',
----> 2                                 n_perm=100, seed=1234, parcellation=parcellation)

~/miniconda3/envs/brainstat/lib/python3.7/site-packages/neuromaps/nulls/nulls.py in alexander_bloch(data, atlas, density, parcellation, n_perm, seed, spins, surfaces)
    111     if data is None:
    112         data = np.arange(len(spins))
--> 113     return load_data(data)[spins]
    114 
    115 

IndexError: index 400 is out of bounds for axis 0 with size 400
``` 

I don't really know what I am missing. Grateful for any input in this regard. Happy to provide further details

Instead of code cells I provide a screenshot below containing my code because vscode does not allow me to copy the outputs of the first code cell. Hope that's fine. 

Cheers,
Marvin

![Screenshot from 2022-01-14 12-37-03](https://user-images.githubusercontent.com/39294105/149508612-9a0c878f-3aa3-46de-b864-fc44a9e2747b.png)
![Screenshot from 2022-01-14 12-37-20](https://user-images.githubusercontent.com/39294105/149508613-2be6c020-b63b-44f2-8fc8-27873f4e5f3c.png)

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Marvin,
Thanks for reaching out! I think the main issue is that the first element in `nulls.alexander_bloch()` should be the parcellated data, not the parcellation labels. Alternatively, you could set `data=None` to return rotated indices instead of rotated data (which is often more convenient because you can reuse the rotations).
Here's an example using the Schaefer 400 Conte69/fsLR parcellation:
```
from netneurotools.datasets import fetch_schaefer2018
from neuromaps.images import dlabel_to_gifti
from neuromaps.nulls import alexander_bloch
schaefer = fetch_schaefer2018('fslr32k')['400Parcels7Networks']
rotated = alexander_bloch(data=None, atlas='fsLR', density='32k', n_perm=100, parcellation=dlabel_to_gifti(schaefer))
```
You could also return a parcellated and rotated brain map by doing something like:
```
from neuromaps.datasets import fetch_annotation
from neuromaps.parcellate import Parcellater
fcgradient = fetch_annotation(source='margulies2016', desc='fcgradient01')
parc = Parcellater(dlabel_to_gifti(schaefer), 'fsLR')
fcgradient_parc = parc.fit_transform(fcgradient, 'fsLR')
rotated = alexander_bloch(data=fcgradient_parc, atlas='fsLR', density='32k', n_perm=100, parcellation=dlabel_to_gifti(schaefer))
```
By the way, I used [netneurotools](https://netneurotools.readthedocs.io/en/latest/) to fetch the Schaefer atlas but you can of course fetch the atlas from elsewhere. If you're looking for a straightforward way of converting the parcellation to `neuromaps`' preferred `gifti` format, try looking in `neuromaps.images` which has a lot of useful conversion functions :slightly_smiling_face:
I hope that helps! Let me know if you run into other issues, or if you have suggestions for how we can improve our documentation (which is still a work in progress).
Justine

**Comment by m-petersen** [comment]
Dear Justine,

thanks so much for your detailed reply. I'll follow your recommendations as soon as I get out of quarantine. ;)

Cheers,
Marvin

**Comment by m-petersen** [comment]
Worked fine following your recommendations. Thanks!
