### ISSUE TITLE
Is it possible to build a spatial null model with a single hemisphere?

### ISSUE THREAD

**Issue by annchenruth** [netneurolab/neuromaps#56]
### Description of issue

I'm looking to compare the developmental and evolutionary expansion maps to some maps from my study, and they're only available in the R hemisphere - is it still possible to build a spatial null model for these, and how would I go about doing it?  Thanks!

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Heyo!

Good point - neuromaps doesn't currently return single-hemisphere nulls. That said, for surface based nulls, the spins are applied on each hemisphere separately so to grab the right hemisphere, you'd just need to grab the indices that refer to the right hemisphere (in the case of fsLR, that would be the second half of the data).

Here's an example of how you could grab the rotated indices for fsLR 164k right hemisphere (which you could reuse for the devexp and evoexp maps):
```
from neuromaps import nulls
spins = nulls.alexander_bloch(data=None, atlas='fsLR', density='164k', n_perm=1000)
spins = spins[int(spins.shape[0]/2):, :]
```
By the way, since you're working with evolutionary expansion maps, I just want to point out that there is a new-ish evolutionary expansion map on neuromaps that you might not have seen if you're working with an older version of neuromaps (`('xu2020', 'evoexp', 'fsLR', '32k')`). Try `pip install git+https://github.com/netneurolab/neuromaps` to upgrade neuromaps to the latest version on github.

Hope that helps!

Justine

**Comment by annchenruth** [comment]
Thanks, this did the trick!
