### ISSUE TITLE
Use of spatial nulls on bilateral brain maps

### ISSUE THREAD

**Issue by zhenglukai** [netneurolab/neuromaps#87]
Hi dear community!

I would like to generate surrogate maps for a parcellated bilateral neocortical map (e., amyloid PET images processed in MNI152 space, masked by a GM mask, and then parcellated using the [200-ROI Schaefer atlas](https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI/Schaefer2018_200Parcels_7Networks_order_FSLMNI152_2mm.nii.gz)) using `neuromaps.nulls.burt2020`. Currently I am doing it like this:

> nulls.burt2020( data = `abeta_sf200_array`, atlas = `'mni152'`, density = `'2mm'`, 
>                parcellation = `'/Volumes/Users/lzheng/templates/schaefer7/Schaefer2018_200Parcels_7Networks_order_FSLMNI152_2mm_GM_masked.nii'`, 
> n_perm = `1000`, seed = `123`, n_proc = `15` )

1. May I ask if I'm using the function correctly?
2. I read from [this brainsmash issue](https://github.com/murraylab/brainsmash/issues/12) by @rmarkello that additional treatment of data (i.e., the Euclidean distance matrix) may be needed to generate bilateral surrogates. In my case, how did `neuromaps` deal with my parcellation file? Specifically, did it generate distance matrix per hemisphere?

Thank you in advance. 😄 

Best,
Lukai

**Comment by VinceBaz** [comment]
Hey @zhenglukai, sorry for the delay!

1. Yes, you are using the function correctly :smile: 

2. This is a good question. In your specific case, neuromaps did not generate a separate distance matrix for each hemisphere. That is because your parcellation and atlas are volumetric. In such cases, neuromaps relies on [`nulls._vol_surrogates`](https://github.com/netneurolab/neuromaps/blob/76ef87315610be13abbc6e1fe3d85afd736c1410/neuromaps/nulls/nulls.py#L442) to compute the distance between every single voxel from both hemisphere. You effectively end up with one bilateral distance matrix. 

In the brainsmash issue you are referring to, Ross uses a surface-based atlas. In this case, we have separate gifti files for each hemisphere and one must either generate surrogate maps for each hemisphere separately or generate a 2N x 2N distance matrix with NaNs/INFs for off-diagonal matrix elements).

A relevant point that was made in this brainsmash issue that applies here, however, is the fact that the null maps that you will generate using a volumetric parcellation won't be symmetric across hemispheres. In his reply, Joshua explains why you might want that (i.e. control for this bilateral symmetry that exists in biological brain maps). If you want to generate null maps that are symmetric across hemisphere, I suggest you use a "spin" null models instead (e.g. [`nulls.alexander_bloch`](https://github.com/netneurolab/neuromaps/blob/76ef87315610be13abbc6e1fe3d85afd736c1410/neuromaps/nulls/nulls.py#L129)). Those models generate nulls that are symmetric across hemispheres. They require a surface-based parcellation, but since you are using the Schaefer parcellation, it shouldn't be a problem (they are available in fsaverage space [here](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/FreeSurfer5.3)).

I hope my answer was useful. Let me know if you have any other question!

Best,
Vince

**Comment by zhenglukai** [comment]
Hi @VinceBaz,

Thank you for your detailed explanation, that helps a lot!

> … I suggest you use a "spin" null models instead. … They require a surface-based parcellation, but since you are using the Schaefer parcellation, it shouldn't be a problem (they are available in fsaverage space [here](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/FreeSurfer5.3)).

Do I understand correctly that to generate spin nulls, the fsaverage parcellation file in `*.annot` format can be applied to my ROI values derived from MNI152 space? In other words, does volume-based processing method introduce "unacceptable" bias in the spin test?

Thanks again and best regards,
Lukai

**Comment by VinceBaz** [comment]
You usually want to minimize the number of transformation between coordinate systems when running an analysis: when possible, it's always better to use brain maps or parcellations in their original coordinate system. 

That being said, when you want to generate surrogate maps for parcellated data (which is your case), we could say that the "original coordinate system" corresponds to the space in which the parcellation was originally defined: it's in this space that the original parcel centroids, which are ultimately what we care about when we generate surrogate maps, were defined. In your case, the Schaefer parcellation was originally defined in the `fsaverage` space. So there is no risk of introducing biases by using the parcel centroids defined in `fsaverage` space, even though your brain map was originally in MNI152 space. 

So yes, you can use the `*annot.` format to generate spin nulls. It might be worth noting however that you'll first want to use the `images.annot_to_gifti` function to convert the annotation file to a `GIFTI` image. And you'll also want to ensure that the labels IDs are consecutive across hemispheres. If they are not, you can use `images.relabel_gifti` :smile:

Hopefully my answer is clear, and let me know if you have any other question!

Best,
Vince

**Comment by zhenglukai** [comment]
Hi Vince,

Thank you so much for your quick and well-explained answer. With that, I now feel more confident about using the spin test. I will close this issue now.

Best,
Lukai
