### ISSUE TITLE
Problem with installing: module 'neuromaps' has no attribute 'datasets'

### ISSUE THREAD

**Issue by pauldhami** [netneurolab/neuromaps#88]
Greetings,

Firstly, thank you for this project.

I am following the instructions to install neuromaps using terminal (on a Mac):

```
git clone https://github.com/netneurolab/neuromaps.git
cd neuromaps
pip install .
```

I then import neuromaps. However, when trying to access any module (e.g., datasets), I run into the following error:

Traceback (most recent call last):

```
  File "/var/folders/g7/2h2flrsx6z75wynfv0s75km80000gn/T/ipykernel_98368/434469093.py", line 1, in <module>
    neuromaps.datasets

AttributeError: module 'neuromaps' has no attribute 'datasets'
```

I was hoping for some assistance with the installation if possible, and what I may be doing wrong (apologizes in advance for something obvious I'm sure I am missing...).

Thank you.

**Comment by VinceBaz** [comment]
Hey @pauldhami,
 
What you did should be correct and you should be able to access the different modules. Can you tell me what was the exact line of code that you used to import neuromaps? On my side, the following lines of code (to access the datasets module) all work: 

```
from neuromaps.datasets import fetch_annotation
fetch_annotation(source='all')
```

```
from neuromaps import datasets
datasets.fetch_annotation(source='all')
```

```
import neuromaps
neuromaps.datasets.fetch_annotation(source='all')
```

Can you also tell me which version of neuromaps you are using? You can know this by running the following line: `neuromaps.__version__`

Thank you.
Vince

**Comment by pauldhami** [comment]
Hi Vince,

Thank you for the reply!

I am using Spyder (Python 3.9) through Anaconda.

On my Mac, I first used the following command in terminal.

```
git clone https://github.com/netneurolab/neuromaps.git
cd neuromaps
pip install .
```

I then use the following command:

`from neuromaps import datasets`

which leads to:

```
from neuromaps import datasets
Traceback (most recent call last):

  File "/var/folders/g7/2h2flrsx6z75wynfv0s75km80000gn/T/ipykernel_98368/780281948.py", line 1, in <module>
    from neuromaps import datasets

ImportError: cannot import name 'datasets' from 'neuromaps' (unknown location)
```

When trying to get the version, I also run into the following error:

```
Traceback (most recent call last):

  File "/var/folders/g7/2h2flrsx6z75wynfv0s75km80000gn/T/ipykernel_98368/830023913.py", line 1, in <module>
    neuromaps.__version__

AttributeError: module 'neuromaps' has no attribute '__version__'
```

I'm assuming I installed it incorrectly?

Thank you for any help.
Best,
Paul

**Comment by VinceBaz** [comment]
The fact that you are using Spyder makes me think that your error might be because you did not install `neuromaps` inside the conda environment that Spyder uses.

Basically, if you look at the bottom right corner of your Spyder window, it should tell you which environement you are using. For instance, for me, it says: `conda: base (Python 3.9.13)`. This means that I am using my `(base)` conda environement. It's probably the same for you. When you install a package you should install it inside this `(base)` environment as well. So what I suggest you do is to open your terminal, and type `conda info`. You'll then want to make sure that the `active environment` is the `(base)` environment. If it is, then you could type `conda list`, to see which package are installed. If `neuromaps` is not on the list, then you might want to try re-installing it.

If you need a more complete guide on how to use conda to install packages, I suggest you look at [this guide](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html).

Let me know if it helped.
Best,
Vince

**Comment by VinceBaz** [comment]
Awesome, I am happy to hear that!

I'll close this issue for now. Feel free to re-open it if anything else happens. 
Best,
Vincent
